name: Build Mac App

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build .app with PyInstaller
        run: |
          pyinstaller --windowed --name "PDF_Manager" PDF.py

      - name: Zip the app
        run: |
          cd dist
          zip -r PDF_Manager.zip PDF_Manager.app

      - name: Upload zipped .app
        uses: actions/upload-artifact@v4
        with:
          name: PDF_Manager-mac
          path: dist/PDF_Manager.zip
